# Generated by Django 5.1.2 on 2024-11-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(choices=[(1, 'Leido'), (2, 'No leido')], default=2),
        ),
    ]
